### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by dlubom** [joona/aws-es-curl#5]
Hello, I get this error on running:

```
[ec2-user@ip-xxx-xx-xx-xx ~]$ aws-es-curl 

/usr/lib/node_modules/aws-es-curl/index.js:14
var getCredentials = function*() {
                             ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/aws-es-curl/bin/aws-es-curl:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by joona** [comment]
Hey, 

codebase uses generators, thus nodejs v4 or above is required. 

I need to update the package.json to reflect the requirement.
