### ISSUE TITLE
Error: Key must be a buffer TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by snakelab** [joona/aws-es-curl#8]
Hi there,

today i got this error:

Error: Key must be a buffer
TypeError: Key must be a buffer
    at new Hmac (crypto.js:115:16)
    at Object.Hmac (crypto.js:113:12)
    at Object.hmac (/usr/local/lib/node_modules/aws-es-curl/node_modules/aws-sdk/lib/util.js:401:30)
    at Object.getSigningKey (/usr/local/lib/node_modules/aws-es-curl/node_modules/aws-sdk/lib/signers/v4_credentials.js:59:8)
    at V4.signature (/usr/local/lib/node_modules/aws-es-curl/node_modules/aws-sdk/lib/signers/v4.js:97:36)
    at V4.authorization (/usr/local/lib/node_modules/aws-es-curl/node_modules/aws-sdk/lib/signers/v4.js:92:36)
    at V4.addAuthorization (/usr/local/lib/node_modules/aws-es-curl/node_modules/aws-sdk/lib/signers/v4.js:34:12)
    at Promise (/usr/local/lib/node_modules/aws-es-curl/index.js:76:12)
    at Promise (<anonymous>)
    at execute (/usr/local/lib/node_modules/aws-es-curl/index.js:58:10)

any hint?

Thanks folks.

Hartmut

**Comment by alloveras** [comment]
Hello @snakelab,
as far as I know, this issue can be caused by two main reasons. See below:

1. If you are not using profiles (see [README.md](https://github.com/joona/aws-es-curl/blob/master/README.md)), it means that you don't have the environment variables `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` configured on the shell where you are executing the `aws-es-curl` command.

    To check this, use something like `printenv` and see if they appear on the output. If they don't, just export them using the following commands:

    `export AWS_ACCESS_KEY_ID=<YOUR AWS KEY ID>`
    `export AWS_SECRET_ACCESS_KEY=<YOUR AWS SECRET ACCESS KEY>`

2. If you are using profiles, it looks like you have something wrong on the profile configuration you are using.

Thanks,

Albert

**Comment by jenseng** [comment]
Unfortunately this can also happen if you use profiles that don't have their own credentials but instead assume a role, e.g.

```
$ cat ~/.aws/credentials
[default]
aws_access_key_id = ABCDEF...
aws_secret_access_key = s3krit...
```

```
$ cat ~/.aws/config
[profile default]
region = us-west-2

[profile foo]
region = us-west-2
role_arn = arn:aws:iam::0123456789012:role/my-role
source_profile = default
```

aws-es-curl doesn't currently supports this scenario, as there is no logic to generate and use AWS.TemporaryCredentials

**Comment by jenseng** [comment]
It looks like this can be worked around by 1. merging your config into your credentials file, e.g.

```
$ cat ~/.aws/credentials
[default]
aws_access_key_id = ABCDEF...
aws_secret_access_key = s3krit...

[foo]
region = us-west-2
role_arn = arn:aws:iam::0123456789012:role/my-role
source_profile = default
```

and 2. inserting this code [on line 36 of index.js](https://github.com/joona/aws-es-curl/blob/0d2198b72cd4626c35cb2fbb45c52bac6aec25cb/index.js#L37):

```
  return credentials.getPromise();
```

I'll create a PR for the latter.

**Comment by joona** [comment]
@jenseng thank you for contributing! this fix is included in  **v1.0.8**
